name: Git Sync
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'DEV-12AM'
        required: true
      email:
        description: 'dev.adbelsalam@gmail.com'
        required: true
      commit_message:
        description: 'Workflow'
        required: true
      default_branch:
        description: 'main'
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout temporary branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'temp-sync' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "${{ github.event.inputs.username }}"
          git config user.email "${{ github.event.inputs.email }}"

      - name: Commit changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "${{ github.event.inputs.commit_message }}"

      - name: Push to default branch
        run: |
          git push origin ${{ github.event.inputs.default_branch }} || {
            echo "Push failed: $?"
            git fetch origin
            git merge origin/${{ github.event.inputs.default_branch }} --no-edit || {
              echo "Merge conflict detected"
              exit 1
            }
            git push origin ${{ github.event.inputs.default_branch }}
          }
