name: Git Sync
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Git Username'
        required: true
      email:
        description: 'Git Email'
        required: true
      commit_message:
        description: 'Commit Message'
        required: true
      default_branch:
        description: 'Default Branch'
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout temporary branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'temp-sync' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "${{ github.event.inputs.username }}"
          git config user.email "${{ github.event.inputs.email }}"

      - name: Commit changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "${{ github.event.inputs.commit_message }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge changes from temp-sync"
          title: "Sync changes from mobile app"
          body: "Automated sync from Syncer app"
          branch: temp-sync
          base: ${{ github.event.inputs.default_branch }}

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --head temp-sync --base ${{ github.event.inputs.default_branch }} --json number -q '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr merge $PR_NUMBER --merge --delete-branch
            echo "Merged PR #$PR_NUMBER and deleted temp-sync"
          else
            echo "No PR found to merge"
          fi
